import { headers } from 'next/headers';
import OkoloBrand from '../okolo-brand.js';

const COPY = {
  de: {
    title: 'Datenschutzerklärung', description: 'Datenschutzerklärung für Okolo — welche Daten wir verarbeiten und warum.',
    intro: 'Kurz gesagt: Die Karte bleibt ohne Account nutzbar. Ein Account ist nur für Beiträge und die geräteübergreifende Merkliste nötig. Keine Werbe-Cookies, so wenig Daten wie möglich — und EU-gehostet, wo es geht.', controller: 'Verantwortlicher',
    processing: 'Was wir verarbeiten', processingItems: [
      <><b>Account & Anmeldung.</b> Du kannst Okolo ohne Anmeldung durchsuchen. Wenn du einen Account nutzt, verarbeitet Supabase deine E-Mail-Adresse, eine Konto-ID, den gewählten Anmeldeanbieter und die notwendigen Sitzungsdaten. Bei „Mit Google fortfahren“ erhält Google die technisch nötige Anmeldeanfrage. Alternativ senden wir dir über Supabase einen Magic Link per E-Mail.</>,
      <><b>Server-Logs & Missbrauchsschutz.</b> Beim Aufruf fällt technisch bedingt deine IP-Adresse an (bei unserem Hoster). Für die Begrenzung von Spam bei Beiträgen speichern wir ausschließlich einen <b>gehashten</b> IP-Wert, nie die IP selbst.</>,
      <><b>Sprache.</b> Beim ersten Aufruf wählen wir anhand des von unserem Hoster bereitgestellten ungefähren IP-Ländercodes Deutsch, Bulgarisch oder Englisch. Deine manuelle Auswahl speichern wir in einem notwendigen First-Party-Cookie und im lokalen Speicher.</>,
      <><b>Nutzungsstatistik.</b> Wir nutzen PostHog (EU-Hosting), um anonym und aggregiert zu verstehen, wie Okolo verwendet wird. Kein Autocapture, keine Session-Aufzeichnung, „Do Not Track“ wird respektiert.</>,
      <><b>Newsletter & Stadt-Benachrichtigung.</b> Wenn du dich anmeldest, speichern wir deine E-Mail-Adresse, die gewählte Newsletter-Ausgabe oder Ortsbezeichnung mit ungefähren Mittelpunkt-Koordinaten (nicht deinen Gerätestandort) und deine Sprache. Für eine verfügbare Ausgabe erhältst du den Wochenend-Newsletter; für eine noch nicht verfügbare Stadt nur eine einmalige Nachricht, sobald dort eine Ausgabe startet. Beides nutzt Double-Opt-in und wird erst nach Klick auf den Bestätigungslink aktiv. Als Nachweis deiner Einwilligung speichern wir Zeitpunkt und Version des Einwilligungstextes sowie einen gehashten IP-Wert (nie die IP selbst). Auswahl ändern oder abmelden kannst du über den Link in jeder E-Mail.</>,
      <><b>Deine Beiträge.</b> Wenn du ein Event/einen Ort hinzufügst oder ein Poster scannst, verarbeiten wir die eingegebenen Inhalte und das Foto und verknüpfen den Beitrag mit deiner Konto-ID. Der veröffentlichte Eintrag wird öffentlich auf der Karte sichtbar; deine E-Mail-Adresse und Konto-ID werden nicht veröffentlicht.</>,
      <><b>Merkliste.</b> Ohne Anmeldung bleibt deine Merkliste nur im lokalen Speicher dieses Geräts. Mit Anmeldung speichern wir die IDs deiner gemerkten Events mit deiner Konto-ID, damit die Liste geräteübergreifend verfügbar ist.</>,
      <><b>Standort.</b> „Meinen Standort finden“ verwendet die Standortfreigabe deines Browsers, um die Karte zu zentrieren. Dieser Standort wird nicht an uns übertragen, außer du gibst bei einem Eintrag bewusst Koordinaten an. Bei der Ortssuche wird deine Eingabe an den Geocoding-Dienst übermittelt.</>,
    ], legal: 'Rechtsgrundlagen', legalItems: ['Betrieb, Sicherheit, Missbrauchsschutz und Sprachauswahl: berechtigtes Interesse (Art. 6 Abs. 1 lit. f DSGVO).', 'Anonyme Nutzungsstatistik: berechtigtes Interesse (Art. 6 Abs. 1 lit. f DSGVO), datensparsam konfiguriert.', 'Account, Anmeldung, Merkliste und die von dir veranlasste Veröffentlichung: Erfüllung der angeforderten Kontofunktionen (Art. 6 Abs. 1 lit. b DSGVO).', 'Newsletter: deine Einwilligung (Art. 6 Abs. 1 lit. a DSGVO), jederzeit widerrufbar.'],
    recipients: 'Empfänger & Auftragsverarbeiter', recipientsItems: [<><b>Vercel</b> — Hosting der Website (USA; Standardvertragsklauseln) und Bereitstellung des ungefähren IP-Ländercodes.</>, <><b>Supabase</b> — Datenbank und Authentifizierung, EU-Projektregion.</>, <><b>Google</b> — Anmeldeanbieter, nur wenn du „Mit Google fortfahren“ wählst (USA; Standardvertragsklauseln).</>, <><b>PostHog</b> — anonyme Nutzungsstatistik, EU-Hosting.</>, <><b>Google (Gemini) bzw. Anthropic (Claude)</b> — nur zur Texterkennung aus einem hochgeladenen Poster (USA; Standardvertragsklauseln). Das Foto wird direkt danach gelöscht.</>, <><b>OpenStreetMap / OpenFreeMap</b> (Kartenkacheln) sowie <b>Nominatim / Photon</b> (Geocoding) — erhalten bei Karten- bzw. Suchanfragen die technisch nötigen Daten.</>],
    retention: 'Speicherdauer', retentionText: 'Account- und Sitzungsdaten bleiben bis zur Löschung deines Accounts bzw. bis zum Ablauf der Sitzung. Deine Merkliste bleibt bis zum Entfernen eines Eintrags oder zur Account-Löschung. Die Verknüpfung deiner Beiträge mit deinem Account bleibt bis zu einer Löschungsanfrage; veröffentlichte Einträge bleiben unabhängig davon, bis sie ablaufen oder entfernt werden. Gehashte IP-Werte für den Missbrauchsschutz werden kurzfristig vorgehalten. Poster-Fotos werden unmittelbar nach der Texterkennung gelöscht. Newsletter-Daten bleiben bis zu deiner Abmeldung; deine Spracheinstellung bis du sie löschst oder 12 Monate lang nicht erneuerst.',
    storage: 'Cookies / lokaler Speicher', storageText: 'Wir setzen keine Werbe-Cookies. Notwendige First-Party-Cookies halten deine Anmeldesitzung und Sprachwahl. Der lokale Speicher merkt Sprache und Merkliste; eine anonyme Statistik-Kennung kann ebenfalls lokal gespeichert werden.',
    rights: 'Deine Rechte', rightsText: <>Du hast das Recht auf Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit und Widerspruch sowie auf Widerruf einer Einwilligung. Schreib an <a href="mailto:hello@okolo.events">hello@okolo.events</a>. Du kannst dich außerdem bei der österreichischen Datenschutzbehörde beschweren (<a href="https://www.dsb.gv.at" target="_blank" rel="noopener noreferrer">dsb.gv.at</a>).</>, updated: 'Stand: September 2026', country: 'Österreich',
  },
  en: {
    title: 'Privacy Policy', description: 'Okolo Privacy Policy — what data we process and why.',
    intro: 'In short: the map remains usable without an account. An account is required only for submissions and cross-device saved events. No advertising cookies, as little data as possible, and EU hosting where feasible.', controller: 'Controller',
    processing: 'What we process', processingItems: [
      <><b>Account & sign-in.</b> You can browse Okolo without signing in. If you use an account, Supabase processes your email address, an account ID, your chosen sign-in provider, and necessary session data. If you choose “Continue with Google”, Google receives the technically required sign-in request. Alternatively, Supabase emails you a magic link.</>,
      <><b>Server logs & abuse prevention.</b> Our host necessarily receives your IP address when you visit. To limit spam in submissions, we store only a <b>hashed</b> IP value, never the IP address itself.</>,
      <><b>Language.</b> On your first visit, we use the approximate IP country code supplied by our host to select German, Bulgarian or English. We store your manual choice in a necessary first-party cookie and local storage.</>,
      <><b>Usage analytics.</b> We use PostHog (EU hosting) to understand Okolo through anonymous, aggregated statistics. Autocapture and session recording are disabled, and “Do Not Track” is respected.</>,
      <><b>Newsletter & city notification.</b> If you sign up, we store your email address, selected newsletter edition or locality with its approximate centre coordinates (not your device location), and language. For an available edition you receive the weekend newsletter; for a city not yet available you receive only one notification when an edition launches there. Both use double opt-in and become active only after you click the confirmation link. As proof of consent we store its time and wording version plus a hashed IP value (never the IP itself). Change your selection or unsubscribe through the link in every email.</>,
      <><b>Your submissions.</b> If you add an event/place or scan a poster, we process the content you enter and the photo and link the submission to your account ID. The published listing is publicly visible on the map; your email address and account ID are not published.</>,
      <><b>Saved events.</b> Without signing in, your saved list stays only in this device’s local storage. When signed in, we store the IDs of your saved events with your account ID so the list is available across devices.</>,
      <><b>Location.</b> “Find my location” uses your browser’s permission to centre the map. The location is not sent to us unless you intentionally provide coordinates for a listing. Location searches are sent to the geocoding service.</>,
    ], legal: 'Legal bases', legalItems: ['Operation, security, abuse prevention and language selection: legitimate interests (Art. 6(1)(f) GDPR).', 'Anonymous usage analytics: legitimate interests (Art. 6(1)(f) GDPR), configured to minimise data.', 'Account, sign-in, saved events, and publication initiated by you: performance of the requested account functions (Art. 6(1)(b) GDPR).', 'Newsletter: your consent (Art. 6(1)(a) GDPR), withdrawable at any time.'],
    recipients: 'Recipients & processors', recipientsItems: [<><b>Vercel</b> — website hosting (USA; Standard Contractual Clauses) and provision of the approximate IP country code.</>, <><b>Supabase</b> — database and authentication, EU project region.</>, <><b>Google</b> — sign-in provider, only if you choose “Continue with Google” (USA; Standard Contractual Clauses).</>, <><b>PostHog</b> — anonymous usage analytics, EU hosting.</>, <><b>Google (Gemini) or Anthropic (Claude)</b> — only to recognise text in a poster you upload (USA; Standard Contractual Clauses). The photo is deleted immediately afterwards.</>, <><b>OpenStreetMap / OpenFreeMap</b> (map tiles) and <b>Nominatim / Photon</b> (geocoding) receive the data technically required for map and search requests.</>],
    retention: 'Retention', retentionText: 'Account and session data remains until you request account deletion or the session expires. Your saved list remains until you remove an item or request account deletion. The link between your account and submissions remains until a deletion request; published listings may remain independently until they expire or are removed. Hashed IP values used for abuse prevention are retained briefly. Poster photos are deleted immediately after recognition. Newsletter data remains until you unsubscribe; your language preference remains until you delete it or it is not renewed for 12 months.',
    storage: 'Cookies / local storage', storageText: 'We use no advertising cookies. Necessary first-party cookies maintain your sign-in session and language choice. Local storage remembers your language and saved list; an anonymous analytics identifier may also be stored locally.',
    rights: 'Your rights', rightsText: <>You have rights of access, correction, deletion, restriction, data portability and objection, and may withdraw consent at any time. Email <a href="mailto:hello@okolo.events">hello@okolo.events</a>. You may also complain to the Austrian Data Protection Authority (<a href="https://www.dsb.gv.at" target="_blank" rel="noopener noreferrer">dsb.gv.at</a>).</>, updated: 'Last updated: September 2026', country: 'Austria',
  },
  bg: {
    title: 'Политика за поверителност', description: 'Политика за поверителност на Okolo — какви данни обработваме и защо.',
    intro: 'Накратко: картата остава достъпна без профил. Профил е нужен само за публикации и синхронизиране на запазени събития между устройства. Без рекламни бисквитки, възможно най-малко данни и хостинг в ЕС, когато е възможно.', controller: 'Администратор',
    processing: 'Какво обработваме', processingItems: [
      <><b>Профил и вход.</b> Можеш да разглеждаш Okolo без вход. Ако използваш профил, Supabase обработва имейл адреса ти, идентификатор на профила, избрания доставчик за вход и необходимите данни за сесията. При „Продължи с Google“ Google получава технически необходимата заявка за вход. Като алтернатива Supabase ти изпраща magic link по имейл.</>,
      <><b>Сървърни логове и защита от злоупотреби.</b> При посещение хостинг доставчикът ни технически получава IP адреса ти. За ограничаване на спама при публикации съхраняваме само <b>хеширана</b> стойност, никога самия IP адрес.</>,
      <><b>Език.</b> При първото посещение използваме приблизителния код на държавата по IP, предоставен от хостинг доставчика, за да изберем немски, български или английски. Ръчният ти избор се пази в необходима бисквитка от първа страна и в локалното хранилище.</>,
      <><b>Статистика за ползването.</b> Използваме PostHog (хостинг в ЕС) за анонимна и обобщена статистика. Автоматичното събиране и записът на сесии са изключени, а “Do Not Track” се спазва.</>,
      <><b>Бюлетин и известие за град.</b> Ако се регистрираш, пазим имейл адреса ти, избраното издание на бюлетина или населено място с приблизителните му централни координати (не местоположението на устройството ти), и езика ти. За налично издание получаваш уикенд бюлетина; за град, който още не е наличен, получаваш само едно известие при старта му. И двете използват двойно потвърждение и стават активни само след клик върху линка. Като доказателство за съгласието пазим момента и версията на текста, както и хеширана стойност на IP адреса (никога самия IP). Можеш да промениш избора си или да се отпишеш чрез линка във всеки имейл.</>,
      <><b>Твоите публикации.</b> Ако добавиш събитие/място или сканираш плакат, обработваме въведеното съдържание и снимката и свързваме публикацията с идентификатора на профила ти. Публикуваният запис се вижда публично на картата; имейлът и идентификаторът ти не се публикуват.</>,
      <><b>Запазени събития.</b> Без вход списъкът остава само в локалното хранилище на устройството. При вход пазим идентификаторите на запазените събития с идентификатора на профила ти, за да са достъпни на различни устройства.</>,
      <><b>Местоположение.</b> „Намери местоположението ми“ използва разрешението на браузъра, за да центрира картата. Местоположението не се изпраща до нас, освен ако съзнателно не добавиш координати към публикация. Търсенията на места се изпращат до услугата за геокодиране.</>,
    ], legal: 'Правни основания', legalItems: ['Работа на услугата, сигурност, защита от злоупотреби и избор на език: легитимен интерес (чл. 6, пар. 1, б. „е“ от ОРЗД).', 'Анонимна статистика: легитимен интерес (чл. 6, пар. 1, б. „е“ от ОРЗД), с минимизиране на данните.', 'Профил, вход, запазени събития и поисканото от теб публикуване: изпълнение на заявените функции на профила (чл. 6, пар. 1, б. „б“ от ОРЗД).', 'Бюлетин: твоето съгласие (чл. 6, пар. 1, б. „а“ от ОРЗД), което можеш да оттеглиш по всяко време.'],
    recipients: 'Получатели и обработващи', recipientsItems: [<><b>Vercel</b> — хостинг на сайта (САЩ; стандартни договорни клаузи) и предоставяне на приблизителния код на държавата по IP.</>, <><b>Supabase</b> — база данни и удостоверяване, проектен регион в ЕС.</>, <><b>Google</b> — доставчик за вход, само ако избереш „Продължи с Google“ (САЩ; стандартни договорни клаузи).</>, <><b>PostHog</b> — анонимна статистика, хостинг в ЕС.</>, <><b>Google (Gemini) или Anthropic (Claude)</b> — само за разпознаване на текст от качен плакат (САЩ; стандартни договорни клаузи). Снимката се изтрива веднага след това.</>, <><b>OpenStreetMap / OpenFreeMap</b> (карта) и <b>Nominatim / Photon</b> (геокодиране) получават технически необходимите данни при заявки към картата и търсачката.</>],
    retention: 'Срок на съхранение', retentionText: 'Данните за профила и сесията остават до заявка за изтриване на профила или изтичане на сесията. Запазеният списък остава до премахване на запис или заявка за изтриване на профила. Връзката между профила и публикациите ти остава до заявка за изтриване; публикуваните записи могат да останат независимо от това, докато изтекат или бъдат премахнати. Хешираните IP стойности за защита от злоупотреби се пазят за кратко. Снимките на плакати се изтриват веднага след разпознаването. Данните за бюлетина остават до отписване; езиковата настройка — докато я изтриеш или ако не бъде подновена 12 месеца.',
    storage: 'Бисквитки / локално хранилище', storageText: 'Не използваме рекламни бисквитки. Необходими бисквитки от първа страна поддържат сесията за вход и избора на език. Локалното хранилище помни езика и запазения списък; възможно е там да се пази и анонимен идентификатор за статистика.',
    rights: 'Твоите права', rightsText: <>Имаш право на достъп, коригиране, изтриване, ограничаване, преносимост и възражение, както и да оттеглиш съгласие по всяко време. Пиши на <a href="mailto:hello@okolo.events">hello@okolo.events</a>. Можеш да подадеш жалба и до австрийския орган за защита на данните (<a href="https://www.dsb.gv.at" target="_blank" rel="noopener noreferrer">dsb.gv.at</a>).</>, updated: 'Актуализирано: септември 2026 г.', country: 'Австрия',
  },
};

async function copy() {
  const lang = (await headers()).get('x-okolo-lang');
  return COPY[lang] || COPY.en;
}

export async function generateMetadata() {
  const t = await copy();
  return { title: t.title, description: t.description, robots: { index: true, follow: true }, alternates: { canonical: '/datenschutz' } };
}

export default async function DatenschutzPage() {
  const t = await copy();
  return (
    <div className="legalpage">
      <OkoloBrand />
      <h1>{t.title}</h1><p className="sub">{t.intro}</p>
      <h2>{t.controller}</h2><p>Georgi Kostov, Breitwiesenstraße 22, Tür 7, 4481 Asten, {t.country}<br /><a href="mailto:hello@okolo.events">hello@okolo.events</a></p>
      <h2>{t.processing}</h2><ul>{t.processingItems.map((item, i) => <li key={i}>{item}</li>)}</ul>
      <h2>{t.legal}</h2><ul>{t.legalItems.map((item, i) => <li key={i}>{item}</li>)}</ul>
      <h2>{t.recipients}</h2><ul>{t.recipientsItems.map((item, i) => <li key={i}>{item}</li>)}</ul>
      <h2>{t.retention}</h2><p>{t.retentionText}</p>
      <h2>{t.storage}</h2><p>{t.storageText}</p>
      <h2>{t.rights}</h2><p>{t.rightsText}</p>
      <p className="updated">{t.updated}</p>
    </div>
  );
}
